### ISSUE TITLE
editor plugin for vscode

### ISSUE THREAD

**Issue by penelopezone** [penelopezone/rubyfmt#125]

**Comment by andrewmcodes** [comment]
I’ll take a crack at it 👍🏼

**Comment by samphippen** [comment]
Please!

Once it's complete open a pull request against this repo with a guide for how to install (imagine that I've never used vscode before).

I'll merge it down and add docs.

**Comment by andrewmcodes** [comment]
I attempted this but ran into some problems and have not been able to come back to it for a few months. If someone else wants to give it a try please do; otherwise, I will try again when I have some time. In the meantime, I believe you can create after-save hooks without creating a plugin for vscode if anyone needs an intermediate solution.

**Comment by wingrunr21** [comment]
Tracking issue:

rubyide/vscode-ruby#445

I will ship support for `v0.2.0` in the next release

**Comment by wingrunr21** [comment]
Just an update here: `v0.25.0` included support
