### ISSUE TITLE
publish as a gem

### ISSUE THREAD

**Issue by mikeyhew** [penelopezone/rubyfmt#139]
>Rubyfmt is a standalone script that only loads the standard library of Ruby, as such it is not packaged as a gem

Even if there are no dependencies, it would still be nice to install rubyfmt with `gem install rubyfmt`, rather than cloning the repository and manually adding it to your PATH. The other nice thing is you could add rubyfmt to your Gemfile and run it with `bundle exec rubyfmt` to make sure that everyone is using the same version.

**Comment by samphippen** [comment]
The problem is that distributing rubyfmt as a gem implies a significant performance penalty that does not happen if it's installed in the system path correctly. I feel like it would irresponsibly encourage bad behaviour (slow command line tooling) to vendor it as a gem, as such I'm deliberately not releasing it as gem.

/cc @searls WDYT?

**Comment by searls** [comment]
Use gel

**Comment by mikker** [comment]
Homebrew / apt / whatever package manager could work, right? So we’d still get automatic(ish) updates.

**Comment by lloeki** [comment]
- Opened PR at Homebrew: https://github.com/Homebrew/homebrew-core/pull/49775
- Opened PR at ArchMac: https://github.com/archmac/packages/pull/12

**Comment by lloeki** [comment]
@penelopezone I feel like it's not because it's distributed and packaged as a gem that it has to be *always* used with Rubygems enabled.

By having `gem install rubyfmt` work, it can be used right away with the caveat that it takes a hit on performance. It's possible to output a message upon `gem install` using `spec.post_install_message` in the gemspec file to warn about that, and instruct the user to `echo "something" > /usr/local/bin/rubyfmt` for awesome performance.†

To me this has the benefit of making rubyfmt extremely usable right away, with one's familiar tooling, at the cost of an openly advertised performance hit. Once the user has discovered the usefulness of rubyfmt, one can then take the next step to enhance performance at one's own discretion.

Case in point, the current `make install` scheme (on v0.2.0 at least) does not support the customary `DEST` env var and installs in `~/bin` right away, which may totally not be what the user wants.

Later down the road this will also have the added bonus that you'll be able to distribute the Rust part as a binary gem.

† I'm wondering if such a script could be included in the gem with a `#!/usr/bin/env ruby --disable=gem`  shebang, and `require_relative` with or without path magic, and the user just has to `ln -s` it into its favorite path location.

**Comment by tragiclifestories** [comment]
I'd just like to pipe up with another use case here which is with code generation. I've got a gem that templates out ruby files and the generated output is valid but hideous (and I don't want to spend the rest of my days fixing all imaginable whitespace issues and whatever else). It would be nice to just be able to do something like this in-process:

```
require "rubyfmt"

def format(input)
   Rubyfmt::Format.call(input)
end
```

I'm not sure what the perf penalties are there, but they probably wouldn't be as bad as our current solution, which is to use prettierrb, which in practice means shelling out to node, which then shells out to another Ruby process to parse the source 🙈 

(Also prettierrb sometimes just doesn't work for completely impenetrable NPM reasons on some people's laptops ... )

**Comment by fables-tales** [comment]
@tragiclifestories rubyfmt is *very* unix friendly in this manner, so you could do that with https://ruby-doc.org/core-2.6.1/Process.html. Given that rubyfmt is statically linked, it wouldn't have the same issue as the one you're describing with prettier. Rubyfmt is very fast (on the order of <20ms for small files), so this would likely be fine
