### ISSUE TITLE
Please help me make a design decision

### ISSUE THREAD

**Issue by penelopezone** [penelopezone/rubyfmt#153]
# Rubyfmt and line breaking for `_mod` expressions

## Background

Rubyfmt forces all lines to be no wider than 80 characters. This is an arbitrary decision but such that
my feelings about autoformatters as strong, this is the one that I'm taking. As such, Rubyfmt has
an algorithm to break expressions on to multiple lines. For example something that looks like this:

```ruby
this_method_name_is_very_long(some_very_long_variable_name_oh_my_god_this_line_is_wide)
```

would have line breaks inserted to look like this:

```ruby
this_method_name_is_very_long(
  some_very_long_variable_name_oh_my_god_this_line_is_wide,
)
```

The important thing to understand is that we ahve the following constraints:

1. Rubyfmt should always output valid Ruby
2. Rubyfmt should prefer constructs that minimise git churn over those that do not
3. Rubyfmt should output Ruby that looks like Ruby rubyists actually write.

## `_mod` expressions

consider an expression like this, where we put a conditional on the end of an expression:

```ruby
a if b
```

this expression parses as a node called `if_mod` in the Ruby parser. You can also `while_mod`, `until_mod`, `unless_mod`
and `rescue_mod`. 

These clauses are most commonly used in contexts like this:

```ruby
return some_expression if some_condition
```

In ruby these are parsed as:

```
[:program,
 [[:if_mod,
   [:vcall, [:@ident, "some_condition", [1, 26]]],
   [:return,
    [:args_add_block,
     [[:vcall, [:@ident, "some_expression", [1, 7]]]],
     false]]]]]
```

note that the return is on the inside of the if_mod.

Here's where things get tricky, as of today the line breaking algorithm in Rubyfmt does this with a long `if_mod`:

```ruby
(
  some_very_long_return_call(
    we_break_args_like_this,
    too,
  )
) if some_conditional
```

and more importantly, does something similar with return expressions:

```ruby
return (
  some_very_long_return_call(
    we_break_args_like_this,
    too,
  )
)
```

Currently, the formatter nests them, because of how it treats multiline statements:

```ruby
(
  return (
    some_very_long_return_call(
      we_break_args_like_this,
      too,
    )
  )
) if some_conditional
```

this is, obviously, super gross. The question I'd like some feedback on is how to fix this problem! 
Below I outline some alternatives, please take a look and tell me which you prefer:

## 🚀 Replace the `_mod` statement with it's multiline version

```ruby
if some_conditional
   return some_very_long_return_call(
     we_break_args_like_this,
     too,
   )
end
```

in the case where we need some breaking, but not full breaking:
```ruby
if some_conditional
  return some_longer_call(a,b,c,d,e,f,g,h,i,j,k)
end
```

## 🦄 `_mod` statement on the line at the end of the broken construct

```ruby
return some_very_long_return_call(
  we_break_args_like_this,
  too,
) if some_condition
```

Note, this case doesn't give us a clean answer where the line is too long where the expression is
too long for 80 chars with the if, but doesn't have inner breakability, e.g.

```ruby
return some_very_long_return_call_but_it_has_no_args_so_we_cant_just_inject_a_paren_to_hang_the_if_off
#where would this even go?
if some_condition
```

## ✨ Return with parens, mod statement on the return

```ruby
return (
  short call but still requires breaking
) if some_condition
```

```ruby
return (
  long_call_where_we_can_break(
     broken_args,
     like_this,
  )
) if some_condition
```

## 😌 just use a slash

```ruby
return whatever_call \
  if something
```

**Comment by penelopezone** [comment]
@tenderlove @cflipse @noelrappin @valeriecodes @samandmoore I'd love your input here, if you could react with the matching emoji for one of the options and some reasoning, that'd be 💯

**Comment by penelopezone** [comment]
oh and @searls obviously

**Comment by noelrappin** [comment]
In practice, I tend to replace with the multiline version, on the theory that the end conditional is only readable if the line is short. Sometimes this is an argument with Rubocop. This isn't something I'd expect the formatter to do, but I also might extract the long call to a variable or another call so that I can use the end conditional.

**Comment by samandmoore** [comment]
I'm have the same tendency as @noelrappin. I prefer splitting it into the multiline conditional format for the same reasons. Long lines that end in a conditional make it so easy to misread the code.

Out of curiosity what happens when the condition is somehow also too long to fit on a single line? Does the formatter split it with a slash? or trailing operator? something else?

**Comment by robotdana** [comment]
i would also prefer a multiline conditional than parens and a trailing conditional, because that's how i'd write code without a formatter

I'd go a step further, trailing conditionals only for very short lines, shorter than the max line length, like: multiline condition if contents is multiple lines or if it was a single line it would be longer than 50 characters or something.

**Comment by tomdalling** [comment]
I vote for the multiline version, because the other options introduce the problem of "oh, I didn't see that thing on the end that completely changes the result". I don't know if there is a name for this smell, so I'm going to call it "sneaky expression continuation". It's the same thing as chaining off an `end` something like this:

```ruby
blah.map do |x|
  # lots
  # of
  # code
  # here
end.compact # <-- sneaky compact
```

Even in the best case, postfix conditionals are still harder to read IMO, so I would only use them on a single, crystal-clear line of code. I think anything over 80 chars, or over multiple lines, is unlikely to be clear enough.

**Comment by mame** [comment]
I talked with @nobu, and we like your first candidate (multiline version).  If the line is so long that it need to be broken, multiline version looks suitable.

Other random ideas:

```
# when the return expression is not so long
return some_expression if
  some_conditional_expression
```

```
# using begin shows the correspondence explicitly
begin
  return long_call(
    arg, arg, arg
  )
end if some_conditional_expression
```

But multiline version is much simpler than them :sweat_smile:

**Comment by penelopezone** [comment]
@mame thank you for replying! I think I'm going to do 🚀  (the one you like) because many people said they also like it!

**Comment by penelopezone** [comment]
I've decided what to do here. Multiline replacement for days.

**Comment by penelopezone** [comment]
It speaks volumes that literally everyone picked rocket

**Comment by searls** [comment]
For what it's worth, my vote would be not to line break at all!
