### ISSUE TITLE
Reconsider position on adopting trailing commas

### ISSUE THREAD

**Issue by penelopezone** [penelopezone/rubyfmt#154]
I love trailing commas in Ruby, but I think we may want to unadopt them. The reason I love trailing commas is that reducing diff noise is one of the most useful (in my opinion) things that an autoformatter can do. The reason that I think we may want to unadopt them is that as I've been building Rubyfmt I've discovered that trailing commas are invalid in vastly more positions than I originally thought. As such, I'm now finding myself hacking in a bunch of special cases, and whenever we find ourselves doing that, we should stop and ask if it's the right thing to do.

This issue outlines most (but not all) of the syntactic cases where trailing commas are interesting/meaningful.

### Collections

Trailing commas are always valid at the end of collections:

```ruby
[
  1,
]

[
  1,
  *a,
]

{
  :a => 1,
}

{
  **a,
}
```

### Method signatures

Trailing commas are not valid at the ends of method signatures

```ruby
def foo(
  a,
)
end

# Traceback (most recent call last):
#        1: from /Users/penelope/.rubies/ruby-2.5.7/bin/irb:11:in `<main>'
# SyntaxError ((irb):7: syntax error, unexpected ')')
```

### Method calls

Trailing commas are valid in method calls, except after a to proc expression:

```ruby
foo(
  a,
)

# this is fine

foo(
  &blk,
)

#Traceback (most recent call last):
#        1: from /Users/penelope/.rubies/ruby-2.5.7/bin/irb:11:in `<main>'
# SyntaxError ((irb):13: syntax error, unexpected ',', expecting ')')
# &blk,
#    ^
```

### Blocks

Trailing commas are valid for non-kwargs to blocks, but are invalid for kwargs

```ruby
a do |
  a,
|
end

# this is fine

a do |a, c:,
|
end

# Traceback (most recent call last):
#        1: from /Users/penelope/.rubies/ruby-2.5.7/bin/irb:11:in `<main>'
# SyntaxError ((irb):19: syntax error, unexpected '|')
```

## Solutions

As far as I can see there are 3 "reasonable" configurations around trailing commas that an autoformatter could choose to adopt, however I am fully open to hearing from others if they have alternate solutions:

### Solution 1: Never insert trailing commas

This one is fairly straightforward, just never put a trailing comma in any multiline construct:

```ruby
[
  a
]

{
  :a => b
}

foo(
  a
)

foo(
  a,
  &blk
)

def foo(
  a
)

a do |
  a
|
end
```

### Solution 2: Only place trailing commas in collection literals

Trailing commas are always valid in collection literals. As such, we could choose to not place trailing commas in any non-collection literal, and always place them in collection literals. This strikes a nice balance between git churn and practicality of implementation and is probably my favourite:

```ruby
[
  a,
]

{
  :a => b,
}

foo(
  a
)

foo(
  a,
  &blk
)

def foo(
  a
)

a do |
  a
|
end
```

### Solution 3: place trailing commas in all legal positions

This proposal is the most complicated to implement but leans hard in to the idea that we want to eliminate git churn. It would place trailing commas in:

* Collection literals
* Method calls, except calls that finish in a to_proc expression
* Block parameters except those that end in kwargs

```ruby
[
  a,
]

{
  :a => b,
}

foo(
  a,
)

foo(
  a,
  &blk
)

def foo(
  a
)

a do |
  a,
|
end
```

# Please help me decide

I'd love a reply in this issue thread, but also if you'd just like to vote, react to this post with a:
* 🚀 for solution 1
* 😃 for solution 2
* 👍  for solution 3

**Comment by geoffharcourt** [comment]
I think 3 will lead to the most eventual adoption, but I worry that's bringing years of corner-case fixing upon you. 2 would still be very useful.

**Comment by penelopezone** [comment]
@geoffharcourt I have very extensive testing around this so I'm not *so* worried about getting it right, but, I am concerned we're setting ourselves up for confusing behaviour.

**Comment by robotdana** [comment]
🚀i like autoformatters to enforce consistency, and catering exactly to ruby’s random comma rules seems the opposite of that

😀also i feel an entirely unfounded feeling that collections are much more likely to churn a single line at a time than method/block calls&definitions so if collections have trailing commas that’s plenty

👍also this might encourage ruby core team to allow trailing commas everywhere? idk

i think i’m mostly team 😀 but it’s close

**Comment by tenderlove** [comment]
I like number two. It seems like how I normally write code.

**Comment by mcmire** [comment]
I think eliminating git churn is a good goal to have. I think one of the reasons I have seen that people get turned off from using any kind of autoformatter, or linter for that matter, is that changes resulting from autoformatting/linting tend to produce noisy diffs. That said, I also feel that an autoformatter should produce code that most people tend to write, and it is extremely rare that I have seen people advocate for or use trailing commas. Therefore I'm for option 1 because it doesn't introduce "weird" syntax and I am doubtful that it would produce as much git churn as option 2 or 3.

**Comment by TheTeaNerd** [comment]
I voted solution 1. I understand the Git churn argument but I don’t find it convincing as it encourages ambiguous code *now* over a _possible_ future, minor inconvenience. YAGNI. When I see a trailing comma, in any language, I’m equally likely to think about the possibility of a bad merge/rebase! Clarity of intent is the most important thing.

**Comment by searls** [comment]
I am for solution 1. I've been using [Standard](https://github.com/testdouble/standard) every day for ~18 months and I'm still not sold on trailing commas of any kind. 

Prior to Standard, I'd never written a trailing comma, primarily because the reason I use Ruby at all is that I can write tersely and without any superfluous keystrokes. The argument that Standard could add these automatically and that they'd reduce git churn seemed to have a lot of support, so we turned on these rules in RuboCop:

```
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
```

And to be honest, in my day-to-day use of Standard, I've never found occasion to appreciate or notice reduced git churn. I think this is because in practice, it is exceptionally rare for me to change a literal without changing its surrounding code, and when a literal is so long that the trailing comma rule would reduce churn, it's of a large data structure whose history does not matter nearly as much as behavioral code would. Apart from this, I'm still irritated often by cases where RuboCop's configuration produces ugly code that also does not accomplish the stated goal of reduced git churn, [like this one](https://github.com/testdouble/standard/issues/133):

```ruby
  Item.find_by_sql([sql, {
      user_id: user.id,
      answer: answer,
    },]).uniq
```

Granted, implementation details of RuboCop are a large part of my frustration (edge cases like the one above are solvable, rubyfmt's autofixer is obviously much faster and less irritating), but because I've also never seen any benefit from this rule in a year and a half of closely watching for it, I'm very inclined to do away with it entirely as unnecessarily complexity / YAGNI

**Comment by mhw** [comment]
I'm 😃 for solution 2. I appreciate the git-churn benefits of trailing commas, but for me that's not the big win: I've become habituated to adding the trailing comma in collections because I just find it makes editing easier more of the time for me.

If I'm typing the initialisation of an array or hash of any size I'll often write one entry and then duplicate the line to create the others and edit each to suit, particularly in the case where the entries have similar structure. When adding new entries I'll then duplicate one of the existing ones. Having all the lines be the same format eliminates the problem of having a missing comma in the middle of the list after one of these edits. So, I might have a piece of code like:

```
{
  avg_metric_1: (source.sum(&:metric_1) / 7.0).round,
  avg_metric_2: (source.sum(&:metric_2) / 7.0).round,
  avg_metric_3: (source.sum(&:metric_3) / 7.0).round,
  total_metric_4: (source.sum(&:metric_4)),
  total_metric_5: (source.sum(&:metric_5)),
}
```

The structural similarity means it is a simpler edit to duplicate an existing line when adding new entries. If the last line omits the trailing comma and I duplicate it or move it up in the initialiser I have to add the comma back in manually otherwise the code has a syntax error. Over the years I've made this mistake enough to develop the habit of always adding (or leaving) the trailing comma for consistency.

I don't think I've built the same habit for arg lists, and I think there might be a couple of reasons:
1. I think I probably don't edit arg lists in the same way: with no data to back it up, my intuition would be that I don't need to reorder arguments or duplicate argument values as often, while it's more common with hashes and arrays.
2. I don't know which languages allow trailing commas in arg lists, and these habits are ones I apply in other languages too. I only recently became aware that Ruby allowed it (with the caveats above), and only know it's been added to JavaScript recently because I just looked it up.

**Comment by bryanp** [comment]
🚀 Solution 1. We should write code that's well-structured for other humans, not for git.

**Comment by mensfeld** [comment]
Sidenote: the order of bullet points does not correspond to order of icons in the "voting section".

This can mislead some ppl (like me) that clicked on an invalid thing assuming, those are aligned.

![Zrzut ekranu z 2020-02-24 16-13-54](https://user-images.githubusercontent.com/392754/75164223-bece9100-5720-11ea-94bf-bf0a09230314.png)

**Comment by joshpuetz** [comment]
I'm team 🚀/Option 1 just because training commas remind me of JavaScript, but I would kick 😄/Option 2 out of my codebase and can appreciate the arguments of reducing git churn.

**Comment by andrewculver** [comment]
I'm for Option 2 (😄) because it seems like a reduction in "git churn" also translates to diffs that are nicer for humans to read and understand. 

One of the most common activities on my software projects is adding a new fields/attributes to existing resources/models. In that scenario, I think [this diff where trailing commas were in use](https://gist.github.com/andrewculver/382c291235d8924a2b61f3344bf0a78a) is a lot nicer to review than [this diff where trailing commas were not in use](https://gist.github.com/andrewculver/99bba8d96c65f37dc701b5f6cc4288a7). In the first example the only things you see are the new attributes. In the latter example you've got "description" making all that noise. Not a huge deal, but one is definitely more readable for humans.

I'm also in favor of Option 2 because, in my experience, having trailing commas in place on multiline arrays and hashes makes it easier to have robots add code like the example above for you automatically without having to actually interpret your Ruby code (which would be a lot more difficult). Even as a human one of the common syntax errors I cause is forgetting to add a comma to the last item when modifying a multiline array or hash.

**Comment by LynxEyes** [comment]
Trailing commas are a nasty idea.
I know, at heart they have good intentions, "oh, lets reduce git diff noise"... But you know what? I read more code than I write, I read more code than I review and I hate seeing dangling comma.

Furthermore, I don't see the git diff situation as noise, it's actually a call to attention.

In the end I don't really care where the implementation is going - I don't see linters as useful things and, to be honest, the XXfmt idea is probably the worst idea that came out of the fairly large number of bad ideas Go introduced...

**Comment by cpruitt** [comment]
My feelings about trailing commas aside, I think a lot of projects currently use them in collection literals. I also think that given the fact that the weird quirks of trailing commas elsewhere seem less widely known, removing a trailing comma after a final kwarg isn't going to kill anyone. So I guess today I'm voting Option 2 (😄). I also feel like I'm going to regret this in the future but since I can't really articulate why I'm going to go ahead and roll the dice.

(For completeness I'll say that I'd **personally** be happier if a formatter just removed all trailing commas. Git churn is pretty low on my list of problems in life.)

**Comment by twe4ked** [comment]
I think it's important to think about the editing case too. We (generally) spend most of our time editing code not writing it for the first time. Having trailing commas makes it easier to re-arrange and add new lines.

**Comment by stevenharman** [comment]
In ranked order: 1, 2, and please not 3. Roughly for the same reasons @searls gave for solution 1, though I’d be OK with 2 if that’s valuable to others. But 3 seems... in-good. The trailing commas in many of those situations, while valid, are confusing, superfluous, and seem like a merge error or sloppy copy/pasta.

**Comment by jasonkarns** [comment]
I'm generally a huge proponent of reducing git-churn (it especially impacts the way I write prose and markdown, etc). However, the impact of git churn has lessened in recent years as more and more (nay, all?) git clients have special highlighting for word-diffs and within-line diffs. Even github highlights the changes within-line in such a way that the impact of git-churn is minimized.

For that reason, I would prefer to not contort my source to appease the limitations of a downstream tool. (at least in the case of trailing commas, where the downstream impact is becoming almost negligible)

I vote 1).

**Comment by penelopezone** [comment]
I'm going to close and lock. My solution here is option 1, no trailing commas anywhere.
