### ISSUE TITLE
Rubyfmt changes semantics of program with cursed string literal

### ISSUE THREAD

**Issue by sgrif** [penelopezone/rubyfmt#166]
* Ruby version: 2.6.5
* Rubyfmt git sha: c44c47610d09f3434f2923abf69e2ee544408e57

## Input file

```ruby
puts <<FOO "foo"
asdfasdf
FOO
```

## Rubyfmt's output

```
puts(
  <<FOO \

asdfasdf
FOO
    "foo"
)
```

## This breaks because

The newline is placed inside the string literal, changing the semantics from "asdfasdf\nfoo" to "\nasdfasdf\nfoo"

**Comment by sgrif** [comment]
I think reasonable output would either be:

```
puts(
  <<~FOO \
    asdfasdf
  FOO
  "foo"
)
```

or

```
Error: wtf is wrong with you
```

**Comment by mcmire** [comment]
Does this happen because of the "consecutive string quirk" in Ruby? Where `"foo" "bar"` is the same as `"foo" + "bar"`? If so, would a more appropriate fix be the following?

``` ruby
puts(<<FOO + "foo")
asdfasdf
FOO
```

**Comment by sgrif** [comment]
`"foo" "bar"` is not the same as `"foo" + "bar"`. One is a string literal, the other is calling the `+` method on `String`. In a hot path, the cost of the additional allocation, memcpy, and potential realloc can be significant

**Comment by reese** [comment]
After #343, this no longer produces semantically different output. It ends up producing the following (well, eventually):

```ruby
puts(
  <<FOO \
asdfasdf
FOO
    "foo"
)
```

However, it does take two runs instead of one to reach this, but I think this is sufficiently different than the semantic issue described here, so I'm going to go ahead and close this out and instead track the parameter multilining issue in #348
