### ISSUE TITLE
Consider telemetry:

### ISSUE THREAD

**Issue by penelopezone** [penelopezone/rubyfmt#177]
Rubyfmt is now approximately very fast:

```
(master)$ wc -l  $FORMAT_FILE && time RUBYFMT_USE_RELEASE=1 ruby --disable=all rubyfmt.rb $FORMAT_FILE > /dev/null
    2294 /Users/penelope/dev/rspec/rspec-dev/repos/rspec-core/lib/rspec/core/configuration.rb

real	0m0.066s
user	0m0.047s
sys	0m0.017s
```
![box plot of timings](https://user-images.githubusercontent.com/96662/78999814-678e4f80-7b19-11ea-9d00-767b9b29cd84.png)

(box plot shows that our upper limit is less than 70ms on a 2000 line file).

What I'd like to do is get a better understanding of the code people are actually writing, so I'm suggesting adding an *opt in* telemetry module that reports back to a central Rubyfmt server. The purpose of this would be largely to help us understand use cases, as well as the kinds of programs people are writing. We'd ensure that the performance impact keeps Rubyfmt well below 70ms per file.

Specifically I think we could count:

1. the length of the file in lines
2. the count of each node type
3. the maximum depth (as measured by re-entrant calls to `format_expression`)
4. basic system information (operating system name/version, ruby name/version)

Specifically we should not include any PII or anything that could be reasonably used to derive the code going through the formatter.

Is this a good idea?

/cc @sgrif @valeriecodes @samandmoore @noelrappin @bestie

**Comment by bestie** [comment]
Definitely a good idea, but comes with some people problems attached. Even the suggestion that data about code is sent somewhere will make some people or their bosses nervous.

I as an enthusiastic participant would still like complete transparency about the data being transmitted. Could that be achieved with any of the following stupid ideas?

- Send the data without TLS (Yikes, but at least I can WireShark it)
- Save a log file on disk and ask me nicely to send it (perhaps give me the curl command)

**Comment by hugo** [comment]
There are two common approaches that I see from the developer focussed tools I use. 

**Ask for permission**
_Examples: VS Code, Atom_

On first run, explain to the user what telemetry you want to to collect and why. Provide an easy opt-out then and there. 


**Ask for forgiveness**
_Examples: Homebrew_

On first run inform the use that telemetry data is being collected. Provide instructions on how to opt out of this if desired. 


Reasonable people can disagree as to the relative palatability of each of these. Personally, I think that for a big company like Microsoft it’s polite to ask to collect. For a small project like rubyfmt I would understand on-by-default. Especially as I trust you, @penelopezone, personally, to not be creepy. Since you are proposing it be off-by-default I am very much in favour of this addition.

**Comment by sholden** [comment]
Reporting back from users is interesting, but could you get a lot of the benefit just by crawling and processing public gems?

**Comment by sgrif** [comment]
I don't think this will give us any information that is particularly helpful for performance optimization that wouldn't show from testing against a few large files (which we have plenty of access to) on our own.
